ln: target '/home/tomasc/genome_analysis_2021/analysis/phylophlan/outdir/data/ppaalns/' is not a directory: No such file or directory
ln: target '/home/tomasc/genome_analysis_2021/analysis/outdir/data/' is not a directory: No such file or directory
Extracting data/ppa.seeds.faa ... Done!
Extracting data/ppafull.aln.faa ... Done!
Extracting data/ppafull.xml ... Done!
Extracting data/ppafull.up2prots.txt ... Done!
Extracting data/ppafull.orgs2prots.txt ... Done!
Extracting data/ppaalns/ppa.aln.tar.bz2 ... Traceback (most recent call last):
  File "/sw/apps/bioinfo/phylophlan/0.99/snowy/bin/phylophlan.py", line 780, in <module>
    init()
  File "/sw/apps/bioinfo/phylophlan/0.99/snowy/bin/phylophlan.py", line 148, in init
    with closing(tarfile.open( f )) as inp:
  File "/sw/comp/python/2.7.11_snowy/lib/python2.7/tarfile.py", line 1673, in open
    return func(name, "r", fileobj, **kwargs)
  File "/sw/comp/python/2.7.11_snowy/lib/python2.7/tarfile.py", line 1738, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "/sw/comp/python/2.7.11_snowy/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: 'data/ppaalns/ppa.aln.tar.bz2'
